pipeline {
  agent any
  stages {
     stage('Checkout Code') {
      steps {
        git 'https://github.com/D-1988/TestNGDemo.git'
        sh "mvn clean install"
      }
    }
    stage('Build') {
      steps {
         sh "mnv test"
      }
    }
    stage('Test') {
      steps {
        echo 'Running tests...'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying application...'
      }
    }
  }
}
