pipeline {
  agent any
  stages {
     stage('Checkout Code') {
      steps {
        git 'https://github.com/D-1988/TestNGDemo.git'
        sh "mvn -Dmaven.test.failure.ignore=true clean package"
      }
    }
    stage('Build') {
      steps {
        echo 'Building the project...'
      }
    }
    stage('Test') {
      steps {
        echo 'Running tests...'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying application...'
      }
    }
  }
}
